$:
  tag_push:
    - services:
      - docker
      stages:
        - name: build
          jobs:
            docker-hub:
              imports: https://cnb.cool/falling42/credentials/-/blob/main/docker-hub.yml
              script: | 
                docker login -u ${FL_USER} -p "${FL_PAT}"
                docker build -f Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} .
                docker push ${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            docker-hub-latest:
              imports: https://cnb.cool/falling42/credentials/-/blob/main/docker-hub.yml
              script: |
                docker login -u ${FL_USER} -p "${FL_PAT}"
                docker build -f Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_REPO_SLUG_LOWERCASE}:latest .
                docker push ${CNB_REPO_SLUG_LOWERCASE}:latest
            cnb:
              script: |
                docker build -f Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} .
                docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            cnb-latest:            
              script: |
                docker build -f Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
                docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        - name: build windows
          jobs:
            docker-hub:
              imports: https://cnb.cool/falling42/credentials/-/blob/main/docker-hub.yml
              script: | 
                docker login -u ${FL_USER} -p "${FL_PAT}"
                docker build -f windows.Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} .
                docker push ${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            docker-hub-latest:
              imports: https://cnb.cool/falling42/credentials/-/blob/main/docker-hub.yml
              script: |
                docker login -u ${FL_USER} -p "${FL_PAT}"
                docker build -f windows.Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_REPO_SLUG_LOWERCASE}:latest .
                docker push ${CNB_REPO_SLUG_LOWERCASE}:latest
            cnb:
              script: |
                docker build -f windows.Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} .
                docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            cnb-latest:            
              script: |
                docker build -f windows.Dockerfile --build-arg CNB_BRANCH=${CNB_BRANCH} -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
                docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest

.build_dev: &build_dev
  script:
    - docker build -f Dockerfile -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} --build-arg CNB_BRANCH=${CNB_BRANCH} . 
    - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}

master:
  push:
    pipeline:
      services:
        - docker
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/falling42/credentials/-/blob/main/env.yml
          settings:
            sync_mode: push
            target_url: https://github.com/Falling42/ssh-deploy.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: Falling42
            git_email: git@falling42.net
dev:
  push:
    test-deploy:
      services:
        - docker
      stages:
        - name: build
          ifModify: 
            - ./scripts/entrypoint.sh
          <<: *build_dev
        - name: ssh deploy
          image: docker.cnb.cool/falling42/ssh-deploy:dev
          imports: https://cnb.cool/falling42/credentials/-/blob/main/env.yml
          settings:
            use_screen: 'yes' # Defaults to no, omit if not needed
            use_jump_host: 'no' # Defaults to no, omit if not needed
            # jump_ssh_host: ${{ secrets.JUMP_SSH_HOST }}
            # jump_ssh_user: ${{ secrets.JUMP_SSH_USER }}
            # jump_ssh_private_key: ${{ secrets.JUMP_SSH_PRIVATE_KEY }}
            # jump_ssh_port: ${{ secrets.JUMP_SSH_PORT }} # Default is 22, omit if not needed
            # ssh_host: ${test_host}
            ssh_host: ${test_host}
            ssh_user: ${ssh_user}
            ssh_private_key: ${ssh_private_key}
            # ssh_port: ${{ secrets.SSH_PORT }} # Default is 22, omit if not needed
            transfer_files: 'yes' # Defaults to yes, as transferring files is a core function of this action :)
            source_file_path: 'test' # Artifact from an upstream job
            destination_path: '/opt/test/' # Ensure the remote server has this directory
            execute_remote_script: 'yes' # Enable this for the following parameters to take effect
            copy_script: 'yes' # If disabled, the deploy_script must already exist on the remote server
            source_script: 'test/test.sh' # Ensure this file exists in your repository
            deploy_script: '/opt/test/test/scripts/test-deploy.sh' # This file will be overwritten each time if copy_script is enabled
            # service_name: 'falling42-test' # Can be hardcoded or use an upstream variable
            # service_version: ${CNB_COMMIT_SHORT} # Populate from upstream variable if needed by your deploy script